#!/usr/bin/env bash
# Idempotent installer for the local pre-commit hook.
#
# Writes a small shim into .git/hooks/pre-commit that execs the real script
# in scripts/pre-commit. That way edits to the hook take effect immediately
# without re-running `make hooks` (and the hook content stays in version
# control where it belongs).

set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
src="$repo_root/scripts/pre-commit"
dst="$repo_root/.git/hooks/pre-commit"

if [ ! -f "$src" ]; then
    echo "install-hooks: $src not found" >&2
    exit 1
fi

mkdir -p "$repo_root/.git/hooks"
cat > "$dst" <<'SHIM'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit.
# Defers to the in-repo hook so updates take effect without reinstalling.
exec "$(git rev-parse --show-toplevel)/scripts/pre-commit" "$@"
SHIM
chmod +x "$dst" 2>/dev/null || true   # chmod is a no-op on NTFS but harmless

echo "Installed pre-commit hook -> $dst (shim -> scripts/pre-commit)"
